[package]
name = "radio_stream"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.42", features = ["derive"] }
config = "0.15.13"
dialoguer = "0.11.0"
inline_colorization = "0.1.6"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
