name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install audio dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -y \
        libjack-dev libasound2-dev libpipewire-0.3-dev \
        libopus-dev libogg-dev opus-tools \
        pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install audio & codec dependencies (macOS)
      run: |
        brew install opus libogg opus-tools pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    
